version: '3.1'
services:

    # The Application
    app:
        build:
            context: ./
            dockerfile: docker/app.dockerfile
        container_name: docker-repertorios
        working_dir: /var/www/application
        volumes:
            - .:/var/www/application
            - ./docker/php.ini.override.ini:/etc/php/7.2/fpm/conf.d/99-overrides.ini
        environment:
            - PHP_IDE_CONFIG=serverName=docker

    # The Web Server
    web:
        image: nginx:alpine
        container_name: docker-repertorios-webserver
        working_dir: /var/www/application
        volumes:
            - .:/var/www/application
            - ./docker/vhost.conf:/etc/nginx/conf.d/default.conf
        ports:
            - 8080:80

    # Mysql
    mysql:
        image: mysql:5.7
        container_name: docker-repertorios-mysql
        working_dir: /var/www/application
        volumes:
        - .:/var/www/application
        environment:
        - MYSQL_ROOT_PASSWORD=dbrootpw
        - MYSQL_DATABASE=setlists
        - MYSQL_USER=dbuser
        - MYSQL_PASSWORD=dbpw
        ports:
        - "8003:3306"
        command:
            --disable-partition-engine-check